export type Role = "CUSTOMER" | "MILL_OWNER" | "DELIVERY"
export type OrderStatus =
  | "PLACED"
  | "ACCEPTED"
  | "GRINDING"
  | "READY"
  | "PICKED_UP"
  | "OUT_FOR_DELIVERY"
  | "DELIVERED"
  | "CANCELLED"
export type GrindTexture = "FINE" | "MEDIUM" | "COARSE"
export type GrainCategory = "WHEAT" | "RICE" | "MILLET" | "PULSES" | "SPICES" | "CORN"
export type PaymentMethod = "CASH" | "UPI"
export type PaymentStatus = "PENDING" | "PAID" | "FAILED"
